apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: "2023-03-08T07:44:36Z"
  generation: 1
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "220696"
  uid: 5e951c0f-e4b6-4753-8c4f-7cdbcb05b159
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
